# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authentication/accountStatus.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='authentication/accountStatus.proto',
  package='authentication',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\"authentication/accountStatus.proto\x12\x0e\x61uthentication*b\n\rAccountStatus\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\r\n\tACTIVATED\x10\x01\x12\x0f\n\x0b\x44\x45\x41\x43TIVATED\x10\x02\x12\n\n\x06LOCKED\x10\x03\x12\x0b\n\x07PENDING\x10\x04\x12\x0b\n\x07\x44\x45LETED\x10\x05\x62\x06proto3'
)

_ACCOUNTSTATUS = _descriptor.EnumDescriptor(
  name='AccountStatus',
  full_name='authentication.AccountStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVATED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEACTIVATED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOCKED', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PENDING', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETED', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=54,
  serialized_end=152,
)
_sym_db.RegisterEnumDescriptor(_ACCOUNTSTATUS)

AccountStatus = enum_type_wrapper.EnumTypeWrapper(_ACCOUNTSTATUS)
DEFAULT = 0
ACTIVATED = 1
DEACTIVATED = 2
LOCKED = 3
PENDING = 4
DELETED = 5


DESCRIPTOR.enum_types_by_name['AccountStatus'] = _ACCOUNTSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
