# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/chat.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb.common import accessInfo_pb2 as common_dot_accessInfo__pb2
from pb.common import replyInfo_pb2 as common_dot_replyInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/chat.proto',
  package='common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11\x63ommon/chat.proto\x12\x06\x63ommon\x1a\x17\x63ommon/accessInfo.proto\x1a\x16\x63ommon/replyInfo.proto\"\xb7\x01\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x03(\t\x12\x0c\n\x04time\x18\x03 \x01(\x03\x12\x0c\n\x04text\x18\x04 \x01(\t\x12!\n\x04type\x18\x05 \x01(\x0e\x32\x13.common.MessageType\x12\n\n\x02id\x18\x06 \x01(\t\x12\x11\n\tsubRoomId\x18\x07 \x01(\t\x12\x10\n\x08language\x18\x08 \x01(\t\x12\x16\n\x0esourceLanguage\x18\t \x01(\t\"c\n\x0f\x43hatSendRequest\x12&\n\naccessInfo\x18\x01 \x01(\x0b\x32\x12.common.AccessInfo\x12(\n\x0b\x63hatMessage\x18\x03 \x01(\x0b\x32\x13.common.ChatMessage\"5\n\rChatSendReply\x12$\n\treplyInfo\x18\x01 \x01(\x0b\x32\x11.common.ReplyInfo\"h\n\x12\x43hatHistoryRequest\x12&\n\naccessInfo\x18\x01 \x01(\x0b\x32\x12.common.AccessInfo\x12\x10\n\x08receiver\x18\x04 \x01(\t\x12\x0c\n\x04\x66rom\x18\x05 \x01(\x03\x12\n\n\x02to\x18\x06 \x01(\x03\"b\n\x10\x43hatHistoryReply\x12$\n\treplyInfo\x18\x01 \x01(\x0b\x32\x11.common.ReplyInfo\x12(\n\x0b\x63hatMessage\x18\x03 \x03(\x0b\x32\x13.common.ChatMessage*>\n\x0bMessageType\x12\r\n\tROOM_CHAT\x10\x00\x12\r\n\tBROADCAST\x10\x01\x12\x11\n\rTRANSCRIPTION\x10\x02\x62\x06proto3'
  ,
  dependencies=[common_dot_accessInfo__pb2.DESCRIPTOR,common_dot_replyInfo__pb2.DESCRIPTOR,])

_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='common.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ROOM_CHAT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BROADCAST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSCRIPTION', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=626,
  serialized_end=688,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETYPE)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
ROOM_CHAT = 0
BROADCAST = 1
TRANSCRIPTION = 2



_CHATMESSAGE = _descriptor.Descriptor(
  name='ChatMessage',
  full_name='common.ChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='common.ChatMessage.sender', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='common.ChatMessage.receiver', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='common.ChatMessage.time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='common.ChatMessage.text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='common.ChatMessage.type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='common.ChatMessage.id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subRoomId', full_name='common.ChatMessage.subRoomId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='common.ChatMessage.language', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sourceLanguage', full_name='common.ChatMessage.sourceLanguage', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=262,
)


_CHATSENDREQUEST = _descriptor.Descriptor(
  name='ChatSendRequest',
  full_name='common.ChatSendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accessInfo', full_name='common.ChatSendRequest.accessInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chatMessage', full_name='common.ChatSendRequest.chatMessage', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=363,
)


_CHATSENDREPLY = _descriptor.Descriptor(
  name='ChatSendReply',
  full_name='common.ChatSendReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='replyInfo', full_name='common.ChatSendReply.replyInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=418,
)


_CHATHISTORYREQUEST = _descriptor.Descriptor(
  name='ChatHistoryRequest',
  full_name='common.ChatHistoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accessInfo', full_name='common.ChatHistoryRequest.accessInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='common.ChatHistoryRequest.receiver', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from', full_name='common.ChatHistoryRequest.from', index=2,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='common.ChatHistoryRequest.to', index=3,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=524,
)


_CHATHISTORYREPLY = _descriptor.Descriptor(
  name='ChatHistoryReply',
  full_name='common.ChatHistoryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='replyInfo', full_name='common.ChatHistoryReply.replyInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chatMessage', full_name='common.ChatHistoryReply.chatMessage', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=624,
)

_CHATMESSAGE.fields_by_name['type'].enum_type = _MESSAGETYPE
_CHATSENDREQUEST.fields_by_name['accessInfo'].message_type = common_dot_accessInfo__pb2._ACCESSINFO
_CHATSENDREQUEST.fields_by_name['chatMessage'].message_type = _CHATMESSAGE
_CHATSENDREPLY.fields_by_name['replyInfo'].message_type = common_dot_replyInfo__pb2._REPLYINFO
_CHATHISTORYREQUEST.fields_by_name['accessInfo'].message_type = common_dot_accessInfo__pb2._ACCESSINFO
_CHATHISTORYREPLY.fields_by_name['replyInfo'].message_type = common_dot_replyInfo__pb2._REPLYINFO
_CHATHISTORYREPLY.fields_by_name['chatMessage'].message_type = _CHATMESSAGE
DESCRIPTOR.message_types_by_name['ChatMessage'] = _CHATMESSAGE
DESCRIPTOR.message_types_by_name['ChatSendRequest'] = _CHATSENDREQUEST
DESCRIPTOR.message_types_by_name['ChatSendReply'] = _CHATSENDREPLY
DESCRIPTOR.message_types_by_name['ChatHistoryRequest'] = _CHATHISTORYREQUEST
DESCRIPTOR.message_types_by_name['ChatHistoryReply'] = _CHATHISTORYREPLY
DESCRIPTOR.enum_types_by_name['MessageType'] = _MESSAGETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatMessage = _reflection.GeneratedProtocolMessageType('ChatMessage', (_message.Message,), {
  'DESCRIPTOR' : _CHATMESSAGE,
  '__module__' : 'common.chat_pb2'
  # @@protoc_insertion_point(class_scope:common.ChatMessage)
  })
_sym_db.RegisterMessage(ChatMessage)

ChatSendRequest = _reflection.GeneratedProtocolMessageType('ChatSendRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHATSENDREQUEST,
  '__module__' : 'common.chat_pb2'
  # @@protoc_insertion_point(class_scope:common.ChatSendRequest)
  })
_sym_db.RegisterMessage(ChatSendRequest)

ChatSendReply = _reflection.GeneratedProtocolMessageType('ChatSendReply', (_message.Message,), {
  'DESCRIPTOR' : _CHATSENDREPLY,
  '__module__' : 'common.chat_pb2'
  # @@protoc_insertion_point(class_scope:common.ChatSendReply)
  })
_sym_db.RegisterMessage(ChatSendReply)

ChatHistoryRequest = _reflection.GeneratedProtocolMessageType('ChatHistoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHATHISTORYREQUEST,
  '__module__' : 'common.chat_pb2'
  # @@protoc_insertion_point(class_scope:common.ChatHistoryRequest)
  })
_sym_db.RegisterMessage(ChatHistoryRequest)

ChatHistoryReply = _reflection.GeneratedProtocolMessageType('ChatHistoryReply', (_message.Message,), {
  'DESCRIPTOR' : _CHATHISTORYREPLY,
  '__module__' : 'common.chat_pb2'
  # @@protoc_insertion_point(class_scope:common.ChatHistoryReply)
  })
_sym_db.RegisterMessage(ChatHistoryReply)


# @@protoc_insertion_point(module_scope)
