# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/languages_BCP47.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/languages_BCP47.proto',
  package='common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1c\x63ommon/languages_BCP47.proto\x12\x06\x63ommon*\xc1\x02\n\x05\x42\x43P47\x12\r\n\tUNDEFINED\x10\x00\x12\t\n\x05\x61r_EG\x10\x64\x12\t\n\x05\x62g_BG\x10n\x12\t\n\x05hr_HR\x10x\x12\t\n\x05\x63s_CZ\x10<\x12\n\n\x05\x64\x61_DK\x10\x82\x01\x12\n\n\x05nl_NL\x10\x8c\x01\x12\t\n\x05\x65n_US\x10\n\x12\t\n\x05\x66i_FI\x10\x0c\x12\t\n\x05\x66r_FR\x10\x1e\x12\t\n\x05\x64\x65_DE\x10\x14\x12\t\n\x05\x65l_GR\x10\x46\x12\n\n\x05he_IL\x10\x9b\x01\x12\n\n\x05hu_HU\x10\xa0\x01\x12\t\n\x05it_IT\x10\x32\x12\n\n\x05lv_LV\x10\xb4\x01\x12\n\n\x05lt_LT\x10\xbe\x01\x12\n\n\x05\x66\x61_IR\x10\xd2\x01\x12\n\n\x05pl_PL\x10\xdc\x01\x12\n\n\x05pt_PT\x10\xe6\x01\x12\n\n\x05ro_RO\x10\xf0\x01\x12\t\n\x05ru_RU\x10P\x12\n\n\x05sk_SK\x10\xfa\x01\x12\n\n\x05sl_SI\x10\x84\x02\x12\t\n\x05\x65s_ES\x10(\x12\n\n\x05sv_SE\x10\x8e\x02\x12\t\n\x05tr_TR\x10Zb\x06proto3'
)

_BCP47 = _descriptor.EnumDescriptor(
  name='BCP47',
  full_name='common.BCP47',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ar_EG', index=1, number=100,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bg_BG', index=2, number=110,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='hr_HR', index=3, number=120,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='cs_CZ', index=4, number=60,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='da_DK', index=5, number=130,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='nl_NL', index=6, number=140,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='en_US', index=7, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='fi_FI', index=8, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='fr_FR', index=9, number=30,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='de_DE', index=10, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='el_GR', index=11, number=70,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='he_IL', index=12, number=155,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='hu_HU', index=13, number=160,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='it_IT', index=14, number=50,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='lv_LV', index=15, number=180,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='lt_LT', index=16, number=190,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='fa_IR', index=17, number=210,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='pl_PL', index=18, number=220,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='pt_PT', index=19, number=230,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ro_RO', index=20, number=240,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ru_RU', index=21, number=80,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sk_SK', index=22, number=250,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sl_SI', index=23, number=260,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='es_ES', index=24, number=40,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sv_SE', index=25, number=270,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='tr_TR', index=26, number=90,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=41,
  serialized_end=362,
)
_sym_db.RegisterEnumDescriptor(_BCP47)

BCP47 = enum_type_wrapper.EnumTypeWrapper(_BCP47)
UNDEFINED = 0
ar_EG = 100
bg_BG = 110
hr_HR = 120
cs_CZ = 60
da_DK = 130
nl_NL = 140
en_US = 10
fi_FI = 12
fr_FR = 30
de_DE = 20
el_GR = 70
he_IL = 155
hu_HU = 160
it_IT = 50
lv_LV = 180
lt_LT = 190
fa_IR = 210
pl_PL = 220
pt_PT = 230
ro_RO = 240
ru_RU = 80
sk_SK = 250
sl_SI = 260
es_ES = 40
sv_SE = 270
tr_TR = 90


DESCRIPTOR.enum_types_by_name['BCP47'] = _BCP47
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
